image:
  - Visual Studio 2019

clone_folder: c:\project\source

clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%

build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake c:\project\source -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE:STRING=Release
  - cmd: cmake --build . --config "Release"
  - cmd: ctest -V